SELECT
    *
FROM
    (
        SELECT
            SUBSTR(CONTRACT_ID, 0, 10) as CONTRACT_ID,
            SUBSTR(MODEL_SUB_TYPE, 0, 2) AS OLD_MODEL_TYPE,
            SUM(CREDIT_LIMIT_NET_EXPOSURE) AS OLD_EXPOSURE,
            SUM(CREDIT_LIMIT_NET_EXPOSURE * ULTIMATE_POD) / SUM(CREDIT_LIMIT_NET_EXPOSURE) AS OLD_PD
        FROM
            CALCXXXX.SO_REPORTING
        WHERE
            MODEL_TYPE = 'IR'
            AND MODEL_SUB_TYPE LIKE '%_COM_%'
        GROUP BY
            CONTRACT_ID,
            SUBSTR(MODEL_SUB_TYPE, 0, 2)
        ORDER BY
            CONTRACT_ID
    ) old FULL OUTER JOIN (
        SELECT
            SUBSTR(CONTRACT_ID, 0, 10) as CONTRACT_ID,
            SUBSTR(MODEL_SUB_TYPE, 0, 2) AS NEW_MODEL_TYPE,
            SUM(CREDIT_LIMIT_NET_EXPOSURE) AS NEW_EXPOSURE,
            SUM(CREDIT_LIMIT_NET_EXPOSURE * ULTIMATE_POD) / SUM(CREDIT_LIMIT_NET_EXPOSURE) AS NEW_PD
        FROM
            CALCXXXX.SO_REPORTING
        WHERE
            MODEL_TYPE = 'IR'
            AND MODEL_SUB_TYPE LIKE '%_COM_%'
        GROUP BY
            CONTRACT_ID,
            SUBSTR(MODEL_SUB_TYPE, 0, 2)
        ORDER BY
            CONTRACT_ID
    ) new ON old.CONTRACT_ID = new.CONTRACT_ID
