select a.CONTRACT_ID, 
a.CUSTOMER_ID, 
a.ALIAS_ID,
a.ULTIMATE_ID,
TRIM('"' FROM (SUBSTR(a.ULTIMATE_NAME, 0, 70))) AS ULTIMATE_NAME,
a.ULTIMATE_ISO_COUNTRY,
a.ULTIMATE_COUNTRY,
a.ULTIMATE_INDUSTRY_SECTOR,
a.ULTIMATE_RATING_TYPE,
a.ULTIMATE_RATING,
a.CREDIT_LIMIT_NET_EXPOSURE,
a.EXPECTED_LOSS,
a.ULTIMATE_POD,
a.EC_CONSUMPTION_ND,
a.ULTIMATE_RSQUARED as RSquared,
a.MODEL_SUB_TYPE

from CALCXXXX.SO_REPORTING a -- update latest CALCRUN

WHERE a.MODEL_TYPE = 'IR'
