-- CODE BELOW IS MEANT TO BE USED IN AUTOMATION DESIGNER
-- IF RUN USING THE EDITOR, SUBSTITUTE "&CALCVAR." FOR THE RUN NUMBER
-- e.g. 6724

SELECT
    CONTRACT_ID,
    CUSTOMER_ID,
    MODEL_SUB_TYPE,
    ALIAS_ID,
    ULTIMATE_ID,
    TRIM(
        '"'
        FROM
            (SUBSTR(ULTIMATE_NAME, 0, 70))
    ) AS ULTIMATE_NAME,
    ULTIMATE_ISO_COUNTRY,
    ULTIMATE_COUNTRY,
    ULTIMATE_INDUSTRY_SECTOR,
    ULTIMATE_RATING_TYPE,
    ULTIMATE_RATING,
    CASE
        WHEN MODEL_SUB_TYPE LIKE '%_COM_%' THEN CREDIT_LIMIT_NET_EXPOSURE
        ELSE 0
    END AS EXP_GROSS_RETRO,
    CASE
        WHEN MODEL_SUB_TYPE LIKE '%_COM_%' THEN ULTIMATE_POD
        ELSE 0
    END AS ULTIMATE_POD,
    EC_CONSUMPTION_ND,
    (SELECT MAX(REPORTING_PERIOD) FROM CALC&CALCVAR..FC_COMPUTED_AMOUNTS) AS REPORTING_PERIOD,
    ('&CALCVAR.') AS CALCRUN
FROM
    CALC&CALCVAR..SO_REPORTING
WHERE
    MODEL_TYPE = 'IR'
